[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.6.3",
    "fastapi>=0.110.0",
    "google-genai>=2.14.0",
    "huggingface-hub>=0.23.0",
    "langchain-core>=0.1.40",
    "langchain-groq>=0.1.0",
    "langchain-openai>=0.1.0",
    "langchain-tavily>=0.1.0",
    "langgraph>=0.0.50",
    "langsmith>=0.10.10",
    "logfire[system-metrics]>=4.39.0",
    "markdown-pdf>=1.13.2",
    "openai>=2.47.0",
    "pillow>=10.0.0",
    "pydantic>=2.7.0",
    "pydantic-settings>=2.2.0",
    "redis>=8.0.1",
    "requests>=2.34.2",
    "slowapi>=0.1.10",
    "tenacity>=8.2.0",
    "uvicorn[standard]>=0.29.0",
]
