from typing import Annotated
from app.services.auth_service import current_user
from app.database import get_db
from app.utils.threadId import generate_id
from app.models import BlogGeneration, User
from app.tasks.blog_tasks import generate_blog_task
from app.config import settings
from app.services.storage import storage
from fastapi import APIRouter,Depends
from app.schemas import UserPrompt, BlogGenerationId, BlogGenerationResponse
from app.agent.graph import graph
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from fastapi import HTTPException,Request
from pathlib import Path
from fastapi.responses import FileResponse,RedirectResponse
from app.limiter import limiter

router = APIRouter()

@router.post(
    "/",
    response_model=BlogGenerationId
)
@limiter.limit("2/minute")
async def generate_blog(
    prompt:UserPrompt,
    current_user:current_user,
    db: Annotated[AsyncSession, Depends(get_db)],
    request:Request
):
    prompt_text = prompt.prompt
    user_id = current_user.id
    thread_id = generate_id()
    
    new_entry = BlogGeneration(
        user_id=user_id,
        thread_id=thread_id,
        prompt=prompt_text,
    )
    
    db.add(new_entry)
    await db.commit()
    await db.refresh(new_entry)
    
    generate_blog_task.delay(thread_id)
    return BlogGenerationId(thread_id=thread_id)

@router.get("/list",response_model=list[BlogGenerationResponse])
async def list_blogs(current_user:current_user,
        db: Annotated[AsyncSession, Depends(get_db)]):
    """Listing all the blogs generated by user"""
    result = await db.execute(select(BlogGeneration).where(BlogGeneration.user_id==current_user.id, BlogGeneration.status=="completed"))
    entries = result.scalars().all()
    print("reached")
    
    return [BlogGenerationResponse(
        thread_id=entry.thread_id,
        status=entry.status,
        current_step=entry.current_step,
        pdf_url=f"/blogs/{Path(entry.pdf_path).name}" if entry.pdf_path else None,
        file_name=Path(entry.pdf_path).name if entry.pdf_path else None,
        error_message=entry.error_message if entry.status == "failed" else None,
    ) for entry in entries]


@router.get("/{blog_id}", response_model=BlogGenerationResponse)
async def get_blog_status(
    blog_id: str,
    current_user: current_user,
    db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(BlogGeneration).where(BlogGeneration.thread_id == blog_id))

    entry = result.scalar_one_or_none()
    if not entry or entry.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Not found")
    return BlogGenerationResponse(
        thread_id=entry.thread_id,
        status=entry.status,
        file_name=Path(entry.pdf_path).name if entry.pdf_path else None,
        current_step=entry.current_step,
        error_message=entry.error_message if entry.status == "failed" else None,
    )

@router.get("/{blog_id}/pdf")
async def view_file(
    blog_id:str,
    current_user:current_user,
    db:Annotated[AsyncSession,Depends(get_db)],
):
    result= await db.execute(select(BlogGeneration).where(BlogGeneration.thread_id == blog_id))
    entry = result.scalar_one_or_none()
    if not entry or entry.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Not found")
    if not entry.pdf_path:
        raise HTTPException(status_code=404, detail="PDF not found")
    if settings.BACKEND == "local":
        key = Path(entry.pdf_path).name
        if storage.exists(key):
            return FileResponse(storage.resolve(key))
        raw = Path(entry.pdf_path)
        if raw.exists():
            return FileResponse(raw)
        raise HTTPException(status_code=404, detail="PDF file missing on disk")
    else:
        key = Path(entry.pdf_path).name
        return RedirectResponse(storage.get_url(key)) # signed S3 URL



@router.post("/{blog_id}/retry")
async def retry_blog(
        blog_id: str,
        current_user: current_user,
        db: Annotated[AsyncSession, Depends(get_db)],
):
    result = await db.execute(select(BlogGeneration).where(BlogGeneration.thread_id == blog_id))
    entry = result.scalar_one_or_none()
    if not entry or entry.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Not found")
    if entry.status != "failed":
        raise HTTPException(status_code=400, detail="Only failed generations can be retried")

    generate_blog_task.delay(blog_id, is_retry=True)
    return {"thread_id": blog_id, "status": "retrying"}



