# def _gemini_generate_image_bytes(prompt: str) -> bytes:
#     """
#     Returns raw image bytes generated by Gemini.
#     Requires: pip install google-genai
#     Env var: GOOGLE_API_KEY
#     """
#     from google import genai
#     from google.genai import types
#     from app.config import settings

#     api_key = settings.GOOGLE_API_KEY

#     if not api_key:
#         raise RuntimeError("GOOGLE_API_KEY is not set.")

#     client = genai.Client(api_key=api_key)

#     resp = client.models.generate_content(
#         model="gemini-2.5-flash-image",
#         contents=prompt,
#         config=types.GenerateContentConfig(
#             response_modalities=["IMAGE"],
#             safety_settings=[
#                 types.SafetySetting(
#                     category="HARM_CATEGORY_DANGEROUS_CONTENT",
#                     threshold="BLOCK_ONLY_HIGH",
#                 )
#             ],
#         ),
#     )

#     parts = getattr(resp, "parts", None)
#     if not parts and getattr(resp, "candidates", None):
#         try:
#             parts = resp.candidates[0].content.parts
#         except Exception:
#             parts = None

#     if not parts:
#         raise RuntimeError("No image content returned (safety/quota/SDK change).")

#     for part in parts:
#         inline = getattr(part, "inline_data", None)
#         if inline and getattr(inline, "data", None):
#             return inline.data

#     raise RuntimeError("No inline image bytes found in response.")

"""
Free image generation via Hugging Face Inference Providers (FLUX.1-schnell).

Setup:
    pip install huggingface_hub pillow
    Create a free Hugging Face account -> https://huggingface.co/settings/tokens
    Add HF_API_TOKEN to your settings/env (same place GOOGLE_API_KEY currently lives)

Notes:
    - Uses provider="auto" instead of hardcoding "hf-inference" directly.
      HF's raw hf-inference backend has been dropping specific models
      (FLUX.1-schnell was pulled from it on 2026-07-15/16) - "auto" routes
      to whichever backend (Together, fal.ai, Replicate, etc.) currently
      serves the model, which is far less brittle than hitting one fixed
      provider's endpoint directly.
    - FLUX.1-schnell is Apache 2.0 licensed -> safe for commercial/B2B use.
    - Free tier gives a monthly credit allotment; if you exceed it you'll
      get a quota/billing error - surfaced clearly below instead of failing
      silently.
    - If FLUX.1-schnell itself ever gets fully deprecated everywhere, check
      current availability at:
      https://huggingface.co/models?pipeline_tag=text-to-image&inference_provider=all
"""

import io

from huggingface_hub import InferenceClient
from huggingface_hub.errors import HfHubHTTPError

from app.config import settings

MODEL_ID = "black-forest-labs/FLUX.1-schnell"


def _hf_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by FLUX.1-schnell via Hugging Face
    Inference Providers (auto-routed to whichever provider currently serves it).

    Requires: pip install huggingface_hub pillow
    Env var: HF_API_TOKEN
    """
    api_token = settings.HF_API_TOKEN

    if not api_token:
        raise RuntimeError("HF_API_TOKEN is not set.")

    client = InferenceClient(api_key=api_token, provider="auto")

    try:
        image = client.text_to_image(prompt, model=MODEL_ID)
    except HfHubHTTPError as e:
        status = getattr(e.response, "status_code", None)
        if status == 429:
            raise RuntimeError("HF rate limit hit (free tier quota exceeded).") from e
        if status in (402, 403):
            raise RuntimeError("HF billing/quota error - out of free credits.") from e
        raise RuntimeError(f"HF inference failed: {e}") from e

    # image is a PIL.Image object - serialize to PNG bytes
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    return buf.getvalue()


if __name__ == "__main__":
    # Quick manual test: python image_gen.py "a red fox in a snowy forest"
    import sys

    test_prompt = sys.argv[1] if len(sys.argv) > 1 else "a red fox in a snowy forest"
    data = _hf_generate_image_bytes(test_prompt)
    with open("test_output.png", "wb") as f:
        f.write(data)
    print(f"Wrote {len(data)} bytes to test_output.png")


