"""add thread_id and error_message to blog_generations

Revision ID: 07650de6dd05
Revises: 77ace6017e81
Create Date: 2026-08-02 21:31:36.564930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07650de6dd05'
down_revision: Union[str, Sequence[str], None] = '77ace6017e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_generations', sa.Column('thread_id', sa.String(length=255), nullable=False))
    op.add_column('blog_generations', sa.Column('prompt', sa.String(length=255), nullable=False))
    op.add_column('blog_generations', sa.Column('pdf_path', sa.String(length=255), nullable=True))
    op.add_column('blog_generations', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('blog_generations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('blog_generations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'blog_generations', ['thread_id'])
    op.drop_column('blog_generations', 'topic')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('blog_generations', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blog_generations', type_='unique')
    op.alter_column('blog_generations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('blog_generations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('blog_generations', 'error_message')
    op.drop_column('blog_generations', 'pdf_path')
    op.drop_column('blog_generations', 'prompt')
    op.drop_column('blog_generations', 'thread_id')
    # ### end Alembic commands ###
